version: '3'
services:
  api:
    build:
      context: .
      dockerfile: "./Dockerfile"
    command: sh ./start-container.sh
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      POSTGRES_DB: "test_backend"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_pwd"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      WAIT_HOSTS: postgres:5432
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: "test_backend"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "test_pwd"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
